⚡️does handle when email is not send
mundipagg/magento2 pull request #308
Opened 2020-12-16 19:36 UTC by wallaceSF

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/MC-0000
| **What?**         | Create treatment when it's not possible to send an e-mail.
| **Why?**          | When the process breaks in the middle
| **How?**          | Adds Try/catch block

2020-12-16 19:52 UTC, nmaia submitted a review, later dismissed

2020-12-16 19:53 UTC, pedrolucasmr submitted a review, later dismissed

2020-12-16 19:54 UTC, michelpl requested changes

2020-12-16 19:54 UTC, michelpl commented on Concrete/Magento2PlatformOrderDecorator.php
> +        $log->info("Try send e-mail: {$message}");
Trying to send the order status by e-mail

2020-12-16 19:54 UTC, michelpl commented on Concrete/Magento2PlatformOrderDecorator.php
> +                $log->info("send e-mail disabled");
The e-mail sending configuration is disabled. E-mail not sent

2020-12-16 19:54 UTC, michelpl commented on Concrete/Magento2PlatformOrderDecorator.php
> +            $log->info("Error send e-mail");
Unable to send e-mail

2020-12-16 19:59 UTC, GabrielDeveloper approved these changes

2020-12-17 12:33 UTC, pedrolucasmr approved these changes

2020-12-21 12:30 UTC, merged