Adds new route to cancel multiple charges
mundipagg/magento2 pull request #332
Opened 2021-05-24 17:31 UTC by yanpantoja

| Questions     | Answers
| ------------- | -------------------------------------------------------
| **Issue**         | https://mundipagg.atlassian.net/browse/PAOP-130
| **What?**         | Adds new route in the API to cancel multiple charges
| **Why?**          | Task requested by the client Galderma.
| **How?**          | Route creation in the webapi.xml file. Creation of class and method used by the api route.

2021-05-26 17:20 UTC, vberardi submitted a review, later dismissed

2021-05-27 12:46 UTC, netorodrigues submitted a review, later dismissed

2021-05-27 15:33 UTC, willian-soaresferreira requested changes
Deixei alguns comentários com sugestões de melhorias em alguns nomes. 

Outra coisa é que reparei que faltam algumas validações sobre obrigatoriedade dos parâmetros, o que acaba ocasionando erros que não ajudam quem fez a request a entender o problema.

Precisa ter validação tanto no parâmetro `requests` (obrigatório) quanto nos parâmetros dentro dele (method, path e params), também obrigatórios, mas nesse caso a validação e mensagem de erro ocorrerá a nível de request mesmo, mas outras requests do array podem funcionar se os parâmetros estiverem corretos. 

E o access_token não deve ser obrigatório e tem que funcionar sem enviar ele (mas se a rota exigir, daremos um erro em cada request). 

Seguem imagens de alguns dos meus testes. E os logs:
```
[2021-05-27 15:21:44] main.CRITICAL: Report ID: webapi-60afb9082723a; Message: Notice: Undefined index: access_token in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 57 {"exception":"[object] (Exception(code: 0): Report ID: webapi-60afb9082723a; Message: Notice: Undefined index: access_token in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 57 at /app/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:205, Exception(code: 0): Notice: Undefined index: access_token in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 57 at /app/lib/internal/Magento/Framework/App/ErrorHandler.php:61)"} []
[2021-05-27 15:22:49] main.CRITICAL: Report ID: webapi-60afb949e1c18; Message: Notice: Undefined index: requests in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 60 {"exception":"[object] (Exception(code: 0): Report ID: webapi-60afb949e1c18; Message: Notice: Undefined index: requests in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 60 at /app/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:205, Exception(code: 0): Notice: Undefined index: requests in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 60 at /app/lib/internal/Magento/Framework/App/ErrorHandler.php:61)"} []
[2021-05-27 15:23:34] main.CRITICAL: Report ID: webapi-60afb976641f5; Message: Notice: Undefined index: method in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 69 {"exception":"[object] (Exception(code: 0): Report ID: webapi-60afb976641f5; Message: Notice: Undefined index: method in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 69 at /app/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:205, Exception(code: 0): Notice: Undefined index: method in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 69 at /app/lib/internal/Magento/Framework/App/ErrorHandler.php:61)"} []
[2021-05-27 15:23:45] main.CRITICAL: Report ID: webapi-60afb981a092f; Message: Notice: Undefined index: path in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 70 {"exception":"[object] (Exception(code: 0): Report ID: webapi-60afb981a092f; Message: Notice: Undefined index: path in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 70 at /app/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:205, Exception(code: 0): Notice: Undefined index: path in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 70 at /app/lib/internal/Magento/Framework/App/ErrorHandler.php:61)"} []
[2021-05-27 15:24:44] main.CRITICAL: Report ID: webapi-60afb9bcc49fa; Message: Notice: Undefined index: params in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 71 {"exception":"[object] (Exception(code: 0): Report ID: webapi-60afb9bcc49fa; Message: Notice: Undefined index: params in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 71 at /app/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:205, Exception(code: 0): Notice: Undefined index: params in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 71 at /app/lib/internal/Magento/Framework/App/ErrorHandler.php:61)"} []
[2021-05-27 15:26:16] main.CRITICAL: Report ID: webapi-60afba186cc80; Message: Warning: Invalid argument supplied for foreach() in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 60 {"exception":"[object] (Exception(code: 0): Report ID: webapi-60afba186cc80; Message: Warning: Invalid argument supplied for foreach() in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 60 at /app/lib/internal/Magento/Framework/Webapi/ErrorProcessor.php:205, Exception(code: 0): Warning: Invalid argument supplied for foreach() in /app/vendor/mundipagg/mundipagg-magento2-module/Model/Api/Bulk.php on line 60 at /app/lib/internal/Magento/Framework/App/ErrorHandler.php:61)"} []

```

Desculpe por não ter especificado no DoD da tarefa também.

2021-05-27 17:05 UTC, yanpantoja commented on Model/Api/Bulk.php
> +        \Magento\Framework\HTTP\Client\Curl $curl,
Show, corrigido!

2021-05-27 17:05 UTC, yanpantoja commented on Model/Api/Bulk.php
> +    private function getChargeUrl(): string
Corrigido

2021-05-27 17:05 UTC, yanpantoja commented on Model/Api/Bulk.php
> +            $curlResponseRequest = $this->curl;
Isso, alterado!

2021-05-27 17:23 UTC, willian-soaresferreira commented
<img width="1091" alt="Screen Shot 2021-05-27 at 12 26 19" src="https://user-images.githubusercontent.com/29166727/119869830-1137c800-bef7-11eb-9a50-f4a225e82259.png">
<img width="1095" alt="Screen Shot 2021-05-27 at 12 23 00" src="https://user-images.githubusercontent.com/29166727/119869836-13018b80-bef7-11eb-9365-7ad6a8bc6130.png">
<img width="1095" alt="Screen Shot 2021-05-27 at 12 22 00" src="https://user-images.githubusercontent.com/29166727/119869838-139a2200-bef7-11eb-8bfe-1ed8608f8298.png">

2021-05-27 17:24 UTC, willian-soaresferreira commented
![Screen Shot 2021-05-27 at 12 21 49](https://user-images.githubusercontent.com/29166727/119869970-3d534900-bef7-11eb-9852-ec9aa54cd136.png)

2021-06-01 12:57 UTC, vberardi submitted a review, later dismissed

2021-06-01 16:54 UTC, willian-soaresferreira requested changes

2021-06-01 16:54 UTC, willian-soaresferreira commented on Model/Api/Bulk.php
> +            $validate = $this->validateSingleRequestParams($key, $request);
Sugiro trocar o nome da variável `$validate` por `$validationInfo`, pra ficar mais claro que esse método de validação`validateSingleRequestParams` está retornando informações (como code e message), diferente por exemplo do método `validateRequestsParam` que realmente só valida e dá exception se houver erro, ou por exemplo se tivéssemos outros métodos de validação do tipo `isEmailValid`, que deixaria explícito que retorna um boolean.

2021-06-01 16:54 UTC, willian-soaresferreira commented on Model/Api/Bulk.php
> +            $body = ["message " => $response['message']];
ficou um espaço antes de fechar as aspas em `"message " =>`.

2021-06-01 16:54 UTC, willian-soaresferreira commented on Model/Api/Bulk.php
> +        }
Acho que dá pra melhorar esses 2 ifs, pra se adequar melhor ao _Open/Closed Principle_, deixando até o código similar a como estava antes do commit (usando métodos `getStatus` e `getBody`). 

Podemos criar uma `BulkSingleResponseInterface` por exemplo, e um model `BulkSingleResponse`, e utilizar algo como:
```
$this->responseArray[] = array(
    "index" => $index,
    "status" => $response->getStatus(), // $response seria obrigatoriamente uma instância da classe BulkSingleResponse
    "body" => json_decode($response->getBody(), true), 
    "path" => $request['path'] ?? null,
    "method" => $request['method'] ?? null,
);
```
E podemos ter uma classe Factory, por exemplo `BulkSingleResponseFactory`, que poderá ter os métodos `createFromCurlResponse` e `createFromArrayData`, que seriam chamados antes do `setFormatedResponse`. 

Similar a essa factory do Core que tem os métodos para criar a partir de _postData_ ou _dbData_: https://github.com/pagarme/ecommerce-module-core/blob/master/src/Kernel/Factories/ChargeFactory.php

Exemplo:
```
if ($validationInfo['code'] === self::HTTP_BAD_REQUEST) {
   $responseFactory = new BulkSingleResponseFactory();
   $response = $responseFactory->createFromArrayData($validationInfo);
   $this->setFormatedResponse($key, $response, $request);
}
```

2021-06-04 15:59 UTC, willian-soaresferreira approved these changes

2021-06-04 16:04 UTC, vberardi approved these changes

2021-06-04 17:19 UTC, merged